# set language
language: java

# temporary change permissions on gradle wrapper
before_install:
 - cd open.xtrace
 - chmod +x gradlew
 - cd ..
 - cd open.xtrace.adapters
 - chmod +x gradlew
 - cd ..

# run gradle
script:
 - cd open.xtrace
 - gradle build
